### ISSUE TITLE
RTL-SDR Init error -3

### ISSUE THREAD

**Issue by M0ZJO** [pyrtlsdr/pyrtlsdr#11]
Hello All

Firstly I would like to thank the people who wrote this wrapper, its great!!

I am trying to get the python wrapper "pyrtlsdr" working on Windows, it works fine on Linux
It imports correctly but prints the following error when I try to initialize the Dongle in windows:

Traceback (most recent call last):
File "C:\Users\M0ZJO\Desktop\RA_Astro\FFTPrint Test.py", line 4, in <module>
sdr = RtlSdr()
File "build\bdist.win32\egg\rtlsdr\rtlsdr.py", line 60, in **init**
% (result, device_index))
IOError: Error code -3 when opening SDR (device index = 0)

Many thanks

Jonathan/M0ZJO

**Comment by pointandyshoot** [comment]
I had error code 3 on a fresh install of ubuntu 17.04 VM, running rtl_test gave me the same error and indicated permissions were not set correctly to access the device.
sudo rtl_test worked ok
sudo urh also worked ok, so it's probably a permissions thing.
