### ISSUE TITLE
can't import RtlSdr

### ISSUE THREAD

**Issue by coolchevy** [pyrtlsdr/pyrtlsdr#7]
```
>>> from rtlsdr import RtlSdr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rtlsdr/__init__.py", line 1, in <module>
    from librtlsdr import librtlsdr
  File "rtlsdr/librtlsdr.py", line 35, in <module>
    f = librtlsdr.rtlsdr_get_device_count
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/ctypes/__init__.py", line 366, in __getattr__
    func = self.__getitem__(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/ctypes/__init__.py", line 371, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, rtlsdr_get_device_count): symbol not found
```

Sorry, it is may be my local issue?

**Comment by sotonian** [comment]
Hopefully roger- is still monitoring..

I'm trying to get TinyPython|Panadapter going, eventually on a Raspberry Pi2, but to start with on my desktop (ubuntu-mate 15.10). When I run pyrtlsdr's setup.py I get a compile error (see below regarding the caret location):
       .....    python setup.py install
running install
running build
running build_py
running install_lib
byte-compiling /usr/local/lib/python2.7/dist-packages/rtlsdr/rtlsdraio.py to rtlsdraio.pyc
  File "/usr/local/lib/python2.7/dist-packages/rtlsdr/rtlsdraio.py", line 15
    def __init__(self, func_start, func_stop=None, queue_size=20, *, loop=None):
.............................................................................................^
SyntaxError: invalid syntax

running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/pyrtlsdr-0.1.1.egg-info
Writing /usr/local/lib/python2.7/dist-packages/pyrtlsdr-0.1.1.egg-info

`
The caret is under the , following the * - I'm not sure if github will upset the dot formatting I've added.

I'm no python expert - one idea of this is to learn more about it - so I'm puzzled by this message. My books and searching around haven't helped. I had to change the permissions on /usr/local/lib/python2.7/dist-packages/pyrtlsdr-0.1.1.egg-info so the setup could change it.

I've done the export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib  as it wasn't on the path

Ideas welcome, TIA

Chris

**Comment by roger-** [comment]
Oh it looks like that's a Python 2.7 issue that I need to fix. In the mean time just remove \* and see if that works.

**Comment by nocarryr** [comment]
@roger- Yup, those [unpacking generalizations](https://www.python.org/dev/peps/pep-0448/) introduced in py3.5 are difficult to make backwards compatible.  
I haven't looked through all of the code, but it looks like [this](https://github.com/roger-/pyrtlsdr/blob/master/rtlsdr/rtlsdraio.py#L92-L94) is the only place that class is instantiated:
```
self.async_iter = AsyncCallbackIter(func_start=lambda cb: func_start(cb, num_samples_or_bytes),
                                            func_stop=self.cancel_read_async,
                                            loop=loop)
```
Since the arguments are all named it would seem that the additional `*` unpack could be dropped, but I'd assume you put that there intentionally.

**Comment by sotonian** [comment]
Thanks for the quick reply, much appreciated.

If I remove * and the , I get another error further down:

`byte-compiling /usr/local/lib/python2.7/dist-packages/rtlsdr/rtlsdraio.py to rtlsdraio.pyc
  File "/usr/local/lib/python2.7/dist-packages/rtlsdr/rtlsdraio.py", line 59
    async def __aiter__(self):
..............^

SyntaxError: invalid syntax

`
[github has removed the double underlines around aiter]

If I remove just the * I see:

`byte-compiling /usr/local/lib/python2.7/dist-packages/rtlsdr/rtlsdraio.py to rtlsdraio.pyc
  File "/usr/local/lib/python2.7/dist-packages/rtlsdr/rtlsdraio.py", line 15
    def __init__(self, func_start, func_stop=None, queue_size=20, , loop=None):
...........................................^
SyntaxError: invalid syntax
`

Chris

**Comment by nocarryr** [comment]
Ok, so the solution that I came up with [here](https://github.com/roger-/pyrtlsdr/blob/master/rtlsdr/__init__.py#L19-L21) to avoid importing `rtlsdraio` in incompatible environments only seems to cover cases where the library isn't being installed from pip (git clones only).

An alternative may need to be found, perhaps modifying `setup.py` for Python < 3.5?

**Comment by nocarryr** [comment]
@roger- I may have time later on today to play around with setuptools on my fork (and maybe even build some tests with TravisCI across different versions).

**Comment by sotonian** [comment]
@nocarryr - thanks for your replies.  The file  init.py (with underscores)  is present in the rtlsdr directory below setup.py along with rtlsdraio et al.  I didn't (knowingly) use pip, I got the source via a git clone from the roger- repository

**Comment by roger-** [comment]
@nocarryr

Yeah the \* isn't really necessary, it just forces the async loop parameter to be a keyword only parameter. It's more of a convention it seems

Thanks for your help with this, will merge your fix.

**Comment by nocarryr** [comment]
:thumbsup:

@roger-  I started some work on automated tests with travis-ci btw:
https://github.com/nocarryr/pyrtlsdr/tree/ci-testing

Running the tests themselves would be a bit difficult though without the device present in the build environment, but I'm hoping to find ways of at least having it test for issues like this one... eventually even have tests run with a 'dummy' device

**Comment by roger-** [comment]
I don't have any travis experience, but looks like a good thing to have!

**Comment by nocarryr** [comment]
I didn't either until recently.  I just decided I wanted to figure it out one day to fix stuff on another project.  I'm not an expert by any means, but it's fun to learn

**Comment by electroconvulsivo** [comment]
I'm not sure if this is the place for this... I had an issue: "undefined symbol: rtlsdr_set_bias_tee"

Solved it with export LD_LIBRARY_PATH="/path_to_libs/"

Many thanks!

**Comment by yangtianlei** [comment]
In my case, I don't have the librtlsdr.so.
To fix that,if in Debain/Ubuntu: 
$sudo apt-get install librtlsdr-dev
if in CentOS:
$sudo yum install rtl-sdr-devel
Hope it works.

**Comment by ET313** [comment]
Dear Roger,
I have Windows10 64 bit, Python 3.7.1 with Anaconda3 2018.12 64-bit and run 
python setup.py install
pip install pyrtlsdr –-upgrade
(base) D:\pyrtlsdr-master>pip install pyrtlsdr --upgrade
Requirement already up-to-date: pyrtlsdr in c:\programdata\anaconda3\lib\site-packages\pyrtlsdr-0.2.91-py3.7.egg (0.2.91)

I tried in Anaconda Prompt:
(base) D:\pyrtlsdr-master>python test.py
Traceback (most recent call last):
  File "test.py", line 62, in <module>
    main()
  File "test.py", line 29, in main
    sdr = RtlSdr()
  File "D:\pyrtlsdr-master\rtlsdr\rtlsdr.py", line 133, in __init__
    self.open(device_index, test_mode_enabled, serial_number)
  File "D:\pyrtlsdr-master\rtlsdr\rtlsdr.py", line 172, in open
    % (result, device_index))
OSError: Error code -1 when opening SDR (device index = 0)

(base) D:\pyrtlsdr-master>

or tried our own small myrtldsr.py with content:
import rtlsdr
sdr = RtlSdr()

with this result in pyrtlsdr-master directory:
(base) D:\pyrtlsdr-master>python myrtlsdr.py
Traceback (most recent call last):
  File "myrtlsdr.py", line 2, in <module>
    sdr = RtlSdr()
NameError: name 'RtlSdr' is not defined


and in the other directory:
(base) D:\pyrtlsdr-master\build\lib\rtlsdr>python myrtlsdr.py
Traceback (most recent call last):
  File "myrtlsdr.py", line 1, in <module>
    import rtlsdr
  File "D:\pyrtlsdr-master\build\lib\rtlsdr\rtlsdr.py", line 20, in <module>
    from .librtlsdr import (
ImportError: attempted relative import with no known parent package

or trying your python files:
(base) D:\pyrtlsdr-master\build\lib\rtlsdr>python rtlsdr.py
Traceback (most recent call last):
  File "rtlsdr.py", line 20, in <module>
    from .librtlsdr import (
ModuleNotFoundError: No module named '__main__.librtlsdr'; '__main__' is not a package

(base) D:\pyrtlsdr-master\build\lib\rtlsdr>python librtlsdr.py

(base) D:\pyrtlsdr-master\build\lib\rtlsdr>

Could you please help?

**Comment by nocarryr** [comment]
@ET313 The first error you had:
```
OSError: Error code -1 when opening SDR (device index = 0)```

Is most likely an issue with device drivers and the [librtldsr](https://github.com/librtlsdr/librtlsdr) installation. I would recommend running the `rtl_test` program shipped with the library to see if it communicates with your device.

The second one is just an import issue:
```python
import rtlsdr
sdr = RtlSdr()
```
Should be:
```python
import rtlsdr
sdr = rtldsr.RtlSdr()
```

**Comment by ET313** [comment]
many thanks for helping at import issue!
Running rtl_test.exe program this is the result:
Found 1 device(s):
  0:  ¶â, , SN: ¹

Using device 0: Terratec T Stick PLUS
usb_open error -5
Failed to open rtlsdr device #0.

could you help?

**Comment by nocarryr** [comment]
Hmmm. The description of the error code is "LIBUSB_ERROR_NOT_FOUND" (which isn't very helpful)
Your device is listed as being supported and uses the E4000, but I don't have much else to go off of.
I would check the wiki:
https://osmocom.org/projects/rtl-sdr/wiki/Rtl-sdr

As well as issues on librtldsr:
https://github.com/librtlsdr/librtlsdr

**Comment by RenatZvezdkin** [comment]
i think i found solution, you have to add Path in environmental variables to lib from this link
it worked for me
https://ftp.osmocom.org/binaries/windows/rtl-sdr/

**Comment by sotonian** [comment]
Thanks - I'll give that a try
